#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");

const root = __dirname;

const requiredFiles = [
  "README.md",
  "native_preflight.js",
  "device_smoke_test.js",
  "static_build_config_check.js",
  "static_kotlin_source_check.js",
  "settings.gradle.kts",
  "build.gradle.kts",
  "app/build.gradle.kts",
  "app/src/main/AndroidManifest.xml",
  "app/src/main/res/xml/conductor_accessibility_service.xml",
  "app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt",
  "app/src/main/java/app/conductor/account/AccountSession.kt",
  "app/src/main/java/app/conductor/account/RecordBackedAccountSessionStore.kt",
  "app/src/main/java/app/conductor/account/AccountSessionMobileAuthTokenProvider.kt",
  "app/src/main/java/app/conductor/voice/VoiceSessionService.kt",
  "app/src/main/java/app/conductor/voice/VoiceSessionModels.kt",
  "app/src/main/java/app/conductor/voice/VoiceSessionController.kt",
  "app/src/main/java/app/conductor/voice/SpeechCapture.kt",
  "app/src/main/java/app/conductor/voice/AndroidSpeechCapture.kt",
  "app/src/main/java/app/conductor/voice/RecordingSpeechCapture.kt",
  "app/src/main/java/app/conductor/voice/SpeechOutput.kt",
  "app/src/main/java/app/conductor/voice/AndroidSpeechOutput.kt",
  "app/src/main/java/app/conductor/voice/RecordingSpeechOutput.kt",
  "app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt",
  "app/src/main/java/app/conductor/voice/VoiceIntentClassifier.kt",
  "app/src/main/java/app/conductor/voice/RealtimeModelTransport.kt",
  "app/src/main/java/app/conductor/voice/RecordingRealtimeModelTransport.kt",
  "app/src/main/java/app/conductor/voice/RealtimeSessionTokenProvider.kt",
  "app/src/main/java/app/conductor/voice/MobileAuthTokenProvider.kt",
  "app/src/main/java/app/conductor/voice/RecordingMobileAuthTokenProvider.kt",
  "app/src/main/java/app/conductor/voice/RecordingRealtimeSessionTokenProvider.kt",
  "app/src/main/java/app/conductor/voice/HttpRealtimeSessionTokenProvider.kt",
  "app/src/main/java/app/conductor/voice/FallbackRealtimeSessionTokenProvider.kt",
  "app/src/main/java/app/conductor/voice/ProductionRealtimeModelTransport.kt",
  "app/src/main/java/app/conductor/voice/RealtimeTransportPlan.kt",
  "app/src/main/java/app/conductor/ui/LauncherUiState.kt",
  "app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt",
  "app/src/main/java/app/conductor/operator/accessibility/ConductorAccessibilityService.kt",
  "app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt",
  "app/src/main/java/app/conductor/operator/accessibility/AppOperationSessionStore.kt",
  "app/src/main/java/app/conductor/operator/accessibility/AppOperationApprovalReceiptLedger.kt",
  "app/src/main/java/app/conductor/operator/accessibility/AppOperationQueue.kt",
  "app/src/main/java/app/conductor/operator/accessibility/AppForegroundLauncher.kt",
  "app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt",
  "app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt",
  "app/src/main/java/app/conductor/operator/accessibility/CustomAppPlaybookSeeder.kt",
  "app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt",
  "app/src/main/java/app/conductor/runtime/Domain.kt",
  "app/src/main/java/app/conductor/runtime/SystemClock.kt",
  "app/src/main/java/app/conductor/runtime/ConductorRuntime.kt",
  "app/src/main/java/app/conductor/storage/ConductorRecordStore.kt",
  "app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt",
  "app/src/main/java/app/conductor/storage/AndroidConductorRecordStoreFactory.kt",
  "app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt",
  "app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt",
  "app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt",
  "app/src/main/java/app/conductor/graph/PersonalGraphStore.kt",
  "app/src/main/java/app/conductor/connectors/ConnectorContracts.kt",
  "app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt",
  "app/src/main/java/app/conductor/connectors/MockOutdoorConnectors.kt",
  "app/src/main/java/app/conductor/connectors/DeviceCalendarConnector.kt",
  "app/src/main/java/app/conductor/connectors/OpenMeteoWeatherConnector.kt",
  "app/src/main/java/app/conductor/connectors/DeviceContactsConnector.kt",
  "app/src/main/java/app/conductor/policy/PolicyEngine.kt",
  "app/src/main/java/app/conductor/policy/UserPolicyStore.kt",
  "app/src/main/java/app/conductor/policy/ApprovalDecisionStore.kt",
  "app/src/main/java/app/conductor/context/MockContextBroker.kt",
  "app/src/main/java/app/conductor/planner/OutdoorActivityPlanner.kt",
  "app/src/main/java/app/conductor/tools/ToolRegistry.kt",
  "app/src/main/java/app/conductor/tools/intents/AndroidIntentModels.kt",
  "app/src/main/java/app/conductor/tools/intents/AndroidIntentPlanner.kt",
  "app/src/main/java/app/conductor/tools/intents/AndroidIntentLauncher.kt",
  "app/src/main/java/app/conductor/tools/intents/AndroidContextIntentLauncher.kt",
  "app/src/main/java/app/conductor/tools/intents/RecordingAndroidIntentLauncher.kt",
  "app/src/main/java/app/conductor/audit/AuditLedger.kt"
];

const requiredText = [
  ["app/src/main/AndroidManifest.xml", "android.intent.category.HOME"],
  ["native_preflight.js", "gradle_or_wrapper"],
  ["native_preflight.js", "static_kotlin_source"],
  ["native_preflight.js", "android_sdk"],
  ["native_preflight.js", "adb install -r"],
  ["native_preflight.js", "--strict"],
  ["static_build_config_check.js", "compose_compiler_plugin_declared"],
  ["static_build_config_check.js", "legacy_compose_compiler_extension_removed"],
  ["static_kotlin_source_check.js", "manifest_class_exists"],
  ["static_kotlin_source_check.js", "screen_declares_callback"],
  ["static_kotlin_source_check.js", "to_launcher_state_call"],
  ["device_smoke_test.js", "app.conductor.prototype"],
  ["device_smoke_test.js", "ConductorLauncherActivity"],
  ["device_smoke_test.js", "ConductorAccessibilityService"],
  ["device_smoke_test.js", "adb install -r"],
  ["device_smoke_test.js", "--strict"],
  ["app/src/main/AndroidManifest.xml", "android.permission.INTERNET"],
  ["app/src/main/AndroidManifest.xml", "android.permission.BIND_ACCESSIBILITY_SERVICE"],
  ["app/src/main/AndroidManifest.xml", "android.permission.RECORD_AUDIO"],
  ["app/src/main/java/app/conductor/voice/VoiceSessionModels.kt", "HANDED_OFF"],
  ["app/src/main/java/app/conductor/voice/VoiceSessionController.kt", "voice.partial"],
  ["app/src/main/java/app/conductor/voice/VoiceSessionController.kt", "voice.final"],
  ["app/src/main/java/app/conductor/voice/VoiceSessionController.kt", "voice.interrupted"],
  ["app/src/main/java/app/conductor/voice/VoiceSessionController.kt", "intent.handed_off"],
  ["app/src/main/java/app/conductor/voice/VoiceSessionService.kt", "receivePartialTranscript"],
  ["app/src/main/java/app/conductor/voice/VoiceSessionService.kt", "handoffIntent"],
  ["app/src/main/java/app/conductor/voice/SpeechCapture.kt", "SpeechCaptureCallback"],
  ["app/src/main/java/app/conductor/voice/AndroidSpeechCapture.kt", "SpeechRecognizer"],
  ["app/src/main/java/app/conductor/voice/AndroidSpeechCapture.kt", "RecognizerIntent.ACTION_RECOGNIZE_SPEECH"],
  ["app/src/main/java/app/conductor/voice/AndroidSpeechCapture.kt", "EXTRA_PARTIAL_RESULTS"],
  ["app/src/main/java/app/conductor/voice/AndroidSpeechCapture.kt", "speech_recognition_unavailable"],
  ["app/src/main/java/app/conductor/voice/RecordingSpeechCapture.kt", "onPartialTranscript"],
  ["app/src/main/java/app/conductor/voice/SpeechOutput.kt", "speakDelta"],
  ["app/src/main/java/app/conductor/voice/SpeechOutput.kt", "finishUtterance"],
  ["app/src/main/java/app/conductor/voice/SpeechOutput.kt", "cancel"],
  ["app/src/main/java/app/conductor/voice/AndroidSpeechOutput.kt", "TextToSpeech"],
  ["app/src/main/java/app/conductor/voice/AndroidSpeechOutput.kt", "QUEUE_ADD"],
  ["app/src/main/java/app/conductor/voice/AndroidSpeechOutput.kt", "shutdown"],
  ["app/src/main/java/app/conductor/voice/RecordingSpeechOutput.kt", "utteranceText"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "startOutdoorIntentCapture"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "startMobileIntentCapture"],
  ["app/src/main/java/app/conductor/voice/VoiceIntentClassifier.kt", "app_task"],
  ["app/src/main/java/app/conductor/voice/VoiceIntentClassifier.kt", "general_mobile_intent"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "autonomyMode"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "speechOutput"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "beginUtterance"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "speakDelta"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "finishUtterance"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "streamResponse"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "beginAssistantResponse"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "streamAssistantDelta"],
  ["app/src/main/java/app/conductor/voice/VoiceHandoffRunner.kt", "controller.handoffIntent"],
  ["app/src/main/java/app/conductor/voice/RealtimeModelTransport.kt", "RealtimeModelCallback"],
  ["app/src/main/java/app/conductor/voice/RealtimeModelTransport.kt", "onTransportError"],
  ["app/src/main/java/app/conductor/voice/RecordingRealtimeModelTransport.kt", "allRequests"],
  ["app/src/main/java/app/conductor/voice/RealtimeSessionTokenProvider.kt", "RealtimeSessionToken"],
  ["app/src/main/java/app/conductor/voice/RealtimeSessionTokenProvider.kt", "createSessionToken"],
  ["app/src/main/java/app/conductor/voice/MobileAuthTokenProvider.kt", "bearerToken"],
  ["app/src/main/java/app/conductor/voice/RecordingMobileAuthTokenProvider.kt", "mobile-user:"],
  ["app/src/main/java/app/conductor/voice/RecordingRealtimeSessionTokenProvider.kt", "ephemeral:test"],
  ["app/src/main/java/app/conductor/voice/RecordingRealtimeSessionTokenProvider.kt", "voice:intent_handoff"],
  ["app/src/main/java/app/conductor/voice/HttpRealtimeSessionTokenProvider.kt", "/realtime/session-token"],
  ["app/src/main/java/app/conductor/voice/HttpRealtimeSessionTokenProvider.kt", "HttpURLConnection"],
  ["app/src/main/java/app/conductor/voice/HttpRealtimeSessionTokenProvider.kt", "authTokenProvider"],
  ["app/src/main/java/app/conductor/voice/HttpRealtimeSessionTokenProvider.kt", "Authorization"],
  ["app/src/main/java/app/conductor/voice/HttpRealtimeSessionTokenProvider.kt", "Bearer"],
  ["app/src/main/java/app/conductor/voice/HttpRealtimeSessionTokenProvider.kt", "voice:intent_handoff"],
  ["app/src/main/java/app/conductor/voice/HttpRealtimeSessionTokenProvider.kt", "10.0.2.2:8787"],
  ["app/src/main/java/app/conductor/voice/FallbackRealtimeSessionTokenProvider.kt", "primary.createSessionToken"],
  ["app/src/main/java/app/conductor/voice/FallbackRealtimeSessionTokenProvider.kt", "fallback.createSessionToken"],
  ["app/src/main/java/app/conductor/voice/ProductionRealtimeModelTransport.kt", "sessionTokenProvider"],
  ["app/src/main/java/app/conductor/voice/ProductionRealtimeModelTransport.kt", "realtime_session_token_unavailable"],
  ["app/src/main/java/app/conductor/voice/RealtimeTransportPlan.kt", "SESSION_TOKEN_REQUIRED"],
  ["app/src/main/java/app/conductor/voice/RealtimeTransportPlan.kt", "server_issued_ephemeral_token"],
  ["app/src/main/java/app/conductor/voice/RealtimeTransportPlan.kt", "model_outputs_intents_not_tools"],
  ["app/src/main/java/app/conductor/policy/PolicyEngine.kt", "outbound_message.send"],
  ["app/src/main/java/app/conductor/policy/PolicyEngine.kt", "public_post.create"],
  ["app/src/main/java/app/conductor/policy/PolicyEngine.kt", "Sensitive external actions require exact user approval"],
  ["app/src/main/java/app/conductor/policy/PolicyEngine.kt", "purchase.create"],
  ["app/src/main/java/app/conductor/policy/PolicyEngine.kt", "data.delete"],
  ["app/src/main/java/app/conductor/policy/PolicyEngine.kt", "account_security.change"],
  ["app/src/main/java/app/conductor/policy/UserPolicyStore.kt", "conductor_user_policy"],
  ["app/src/main/java/app/conductor/policy/ApprovalDecisionStore.kt", "conductor_approval_decisions"],
  ["app/src/main/java/app/conductor/runtime/Domain.kt", "ApprovalStatus"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "approvedApprovalIds"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "deniedApprovalIds"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "userId: String"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "saveTask"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "runMobileIntentWorkflow"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "runAppTaskWorkflow"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "runGeneralMobileIntentWorkflow"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "intent.routed"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "gatherOutdoorActivityContext(task, policy.mode)"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "task.context_blocked"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "Context blocked by autonomy"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "approval.granted"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "approval.queued"],
  ["app/src/main/java/app/conductor/account/AccountSession.kt", "AccountSession"],
  ["app/src/main/java/app/conductor/account/AccountSession.kt", "AccountSessionStore"],
  ["app/src/main/java/app/conductor/account/AccountSession.kt", "bearerToken"],
  ["app/src/main/java/app/conductor/account/AccountSession.kt", "defaultAccountSession"],
  ["app/src/main/java/app/conductor/account/RecordBackedAccountSessionStore.kt", "saveAccountSession"],
  ["app/src/main/java/app/conductor/account/RecordBackedAccountSessionStore.kt", "accountSessions"],
  ["app/src/main/java/app/conductor/account/AccountSessionMobileAuthTokenProvider.kt", "MobileAuthTokenProvider"],
  ["app/src/main/java/app/conductor/account/AccountSessionMobileAuthTokenProvider.kt", "currentSession"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "saveGraphFact"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "saveApprovalDecision"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "saveAppAgentGrant"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "appAgentGrants"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "saveAccountSession"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "saveConnectorAccount"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "saveAppOperationSession"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "saveAppOperationPlaybook"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "StoredConsumedApprovalReceipt"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "saveConsumedApprovalReceipt"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "consumedApprovalReceipts"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "enqueueAppOperation"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "resolveQueuedAppOperation"],
  ["app/src/main/java/app/conductor/storage/ConductorRecordStore.kt", "clearQueuedAppOperations"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "approvedIds"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "deniedIds"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "consumedApprovalReceiptRecords"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "saveConsumedApprovalReceipt"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "appAgentGrantRecords"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "accountSessionRecords"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "connectorAccountRecords"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "appOperationSessionRecords"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "appOperationPlaybookRecords"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "appOperationQueueRecords"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "removeAll"],
  ["app/src/main/java/app/conductor/storage/InMemoryConductorRecordStore.kt", "appOperationQueueRecords.clear"],
  ["app/src/main/java/app/conductor/storage/AndroidConductorRecordStoreFactory.kt", "EncryptedSharedPreferences"],
  ["app/src/main/java/app/conductor/storage/AndroidConductorRecordStoreFactory.kt", "MasterKey.KeyScheme.AES256_GCM"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", "class AndroidPreferencesConductorRecordStore"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", "override fun enqueueAppOperation"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", "requiredSourceIds = getJSONArray(\"requiredSourceIds\").toStringSet()"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", ".put(\"primaryActionLabel\", primaryActionLabel)"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", ".put(\"autonomyContext\", autonomyContext)"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", ".put(\"loginProof\", loginProof.toJson())"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", "toAppLoginProof"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", "override fun saveConsumedApprovalReceipt"],
  ["app/src/main/java/app/conductor/storage/AndroidPreferencesConductorRecordStore.kt", "override fun appOperationSessions"],
  ["app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt", "SQLCIPHER_REQUIRED"],
  ["app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt", "account_sessions"],
  ["app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt", "app_agent_grants"],
  ["app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt", "consumed_approval_receipts"],
  ["app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt", "connector_accounts"],
  ["app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt", "app_operation_sessions"],
  ["app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt", "app_operation_playbooks"],
  ["app/src/main/java/app/conductor/storage/AndroidStoragePlan.kt", "app_operation_queue"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "CREATE TABLE app_agent_grants"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "app_agent_id"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "sources_json"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "expires_at_iso TEXT"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "CREATE TABLE graph_facts"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "expires_at_iso TEXT"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "CREATE TABLE account_sessions"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "bearer_token_handle"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "CREATE TABLE connector_accounts"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "CREATE TABLE app_operation_sessions"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "allowed_source_ids_json"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "login_proof_json"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "revoked INTEGER NOT NULL DEFAULT 0"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "CREATE TABLE app_operation_playbooks"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "required_input_keys_json"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "steps_json"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "CREATE TABLE app_operation_queue"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "app_operation_queue_request_id_idx"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "required_source_ids_json"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "primary_action_label"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "autonomy_context"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "approval_id"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "approved_exact_content"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "CREATE TABLE consumed_approval_receipts"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "consumed_at_iso"],
  ["app/src/main/java/app/conductor/storage/AndroidRecordStoreSchema.kt", "summary_ciphertext"],
  ["app/src/main/java/app/conductor/audit/AuditLedger.kt", "appendAudit"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "defaultOutdoorConnectorRuntime"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "ConductorRecordStore"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "AppAgentGrant"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "autonomyMode: AutonomyMode"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "AutonomyMode.ASK_ONLY"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "items = emptyMap()"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "toContextBundleForAppAgent"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "context.restored_from_graph"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "context.cache_miss"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "requiredOutdoorContextKeys"],
  ["app/src/main/java/app/conductor/context/MockContextBroker.kt", "facebook_events"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "AppAgentGrant"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "val expiresAtIso: String? = null"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "!grant.isExpired(nowIso())"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "grantAppAgentAccess"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "toContextBundleForAppAgent"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "autonomyMode: AutonomyMode"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "AutonomyMode.ASK_ONLY"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "hasAppAgentGrant"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "app_agent.snapshot_denied"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "semanticSourceKey"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "\"google_calendar\" -> \"calendar\""],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "\"weather_provider\" -> \"weather\""],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "\"facebook_events\" -> \"events\""],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "allowedPurposes"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "expiresAtIso"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "fun isExpired"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "!fact.isExpired(nowIso())"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "redactedSummary"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "saveGraphFact"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "graphGrants"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "graphFacts"],
  ["app/src/main/java/app/conductor/graph/PersonalGraphStore.kt", "grant_preserved_revoked"],
  ["app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt", "credentialHandle"],
  ["app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt", "saveConnectorAccount"],
  ["app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt", "connectorAccounts()"],
  ["app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt", "connector.accounts_restored"],
  ["app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt", "fun connectedAccounts()"],
  ["app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt", "isGrantRevoked"],
  ["app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt", "grant_revoked"],
  ["app/src/main/java/app/conductor/connectors/ConnectorRuntime.kt", "purpose_not_allowed"],
  ["app/src/main/java/app/conductor/connectors/MockOutdoorConnectors.kt", "vault:facebook:personal"],
  ["app/src/main/java/app/conductor/connectors/MockOutdoorConnectors.kt", "maps"],
  ["app/src/main/java/app/conductor/operator/accessibility/ConductorAccessibilityService.kt", "whitelistedPackages"],
  ["app/src/main/java/app/conductor/operator/accessibility/ConductorAccessibilityService.kt", "AppOperationPlaybookRegistry"],
  ["app/src/main/java/app/conductor/operator/accessibility/ConductorAccessibilityService.kt", "playbookRegistryProvider"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "NEEDS_HANDOFF"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "AppLoginState"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "LOGGED_IN"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "AppOperationSession"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "data class AppLoginProof"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "fun hasLoginProof"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "allowedPlaybookIds"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "requiredInputKeys"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "AppOperationApprovalReceipt"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "approvedExactContent"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "AppOperationQueueItem"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "primaryActionLabel"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "autonomyContext"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "AppAgentRouteStatus"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "AppAgentSurface"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "AppAgentRoute"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "allowedSourceIds"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "revoked: Boolean = false"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "!revoked"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "fun isExpired"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "expiresAtIso <= nowIso"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationModels.kt", "requiredSourceIds"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationSessionStore.kt", "sessionFor"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationSessionStore.kt", "saveSession"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationSessionStore.kt", "InMemoryAppOperationSessionStore"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationSessionStore.kt", "RecordBackedAppOperationSessionStore"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationSessionStore.kt", "AutonomyMode"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationSessionStore.kt", "allowedSourceIds = setOf"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationSessionStore.kt", "default_accessibility_account_chip"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationApprovalReceiptLedger.kt", "AppOperationApprovalReceiptLedger"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationApprovalReceiptLedger.kt", "isConsumed"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationApprovalReceiptLedger.kt", "consume"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationApprovalReceiptLedger.kt", "InMemoryAppOperationApprovalReceiptLedger"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationApprovalReceiptLedger.kt", "RecordBackedAppOperationApprovalReceiptLedger"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationApprovalReceiptLedger.kt", "saveConsumedApprovalReceipt"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationApprovalReceiptLedger.kt", "StoredConsumedApprovalReceipt"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationQueue.kt", "enqueue"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationQueue.kt", "pending"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationQueue.kt", "resolve"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationQueue.kt", "clear"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationQueue.kt", "InMemoryAppOperationQueue"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationQueue.kt", "RecordBackedAppOperationQueue"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "messages_send_exact_text"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "calendar_create_tentative_hold"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "maps_open_route"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "facebook_create_post_exact_text"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "customPlaybooks"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "builtInPlaybooks"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "RecordBackedAppOperationPlaybookRegistryProvider"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "recordStore.appOperationPlaybooks()"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "com.facebook.katana"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "composer_text_equals input.exactBody"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "requiresExactApproval"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationPlaybookRegistry.kt", "requiredInputKeys = setOf"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "class AppAgentOnboarding"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "fun onboard"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "saveAppOperationPlaybook"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "saveAppOperationSession"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "observed_accessibility_tree_dry_run"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "allowedSourceIds"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "observedTreeLabels"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "observedTreeLabelCounts"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "dryRun"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "AppAgentPlaybookDryRun"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "observed_tree_required"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "target_ambiguous"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "verifier_ambiguous"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "associateWith { 1 }"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "app_agent.playbook_dry_run_verified"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "app_agent.onboarded"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "app_agent.onboarding_blocked"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppAgentOnboarding.kt", "sensitive_playbook_requires_exactBody"],
  ["app/src/main/java/app/conductor/operator/accessibility/CustomAppPlaybookSeeder.kt", "generic_notes_append_exact_text"],
  ["app/src/main/java/app/conductor/operator/accessibility/CustomAppPlaybookSeeder.kt", "community_board_create_post_exact_text"],
  ["app/src/main/java/app/conductor/operator/accessibility/CustomAppPlaybookSeeder.kt", "com.example.notes"],
  ["app/src/main/java/app/conductor/operator/accessibility/CustomAppPlaybookSeeder.kt", "com.example.community"],
  ["app/src/main/java/app/conductor/operator/accessibility/CustomAppPlaybookSeeder.kt", "requiredInputKeys = setOf"],
  ["app/src/main/java/app/conductor/operator/accessibility/CustomAppPlaybookSeeder.kt", "saveAppOperationPlaybook"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "sessionStore.sessionFor"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "routeAction"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "executeRouted"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "registryProvider: () -> AppOperationPlaybookRegistry"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "val currentRegistry = registryProvider()"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "currentRegistry.forAction"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "currentRegistry.find"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "nowIso: () -> String"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "agent_route.ready"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "agent_route.needs_login"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "!session.hasLoginProof()"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "agent_route.session_expired"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "session_expired"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "session.isExpired(nowIso())"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "source_grant_required"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "playbook_grant_required"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "app_agent_revoked"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.queued"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "queuedOperations"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "requiresExactApproval"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "approvalReceiptLedger"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.approval_replay_blocked"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.approval_consumed"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "Approval receipt already used"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "playbook.requiredInputKeys.ifEmpty"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.exact_approval_verified"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "Exact approval receipt missing or mismatched"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "evaluateSessionAutonomy"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.autonomy_checked"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.autonomy_handoff"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "Apply autonomy and retry"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "Review inputs"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "Confirm login and grant"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "auditDetail"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "App session autonomy ASK_ONLY"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "LOW_RISK_AUTO app session"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "AppOperationAutonomyDecision"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.needs_handoff"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.blocked"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "operator.verified"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "post_state_receipt"],
  ["app/src/main/java/app/conductor/operator/accessibility/AppOperationExecutor.kt", "public_post.create"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "AppOperationExecutor"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "executeRouted"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "requiredSourceIdsFor"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "userId: String"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "AndroidIntentPlanner"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "AndroidIntentLauncher"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "intent.planned"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "intent.launch_result"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "facebook.post"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "approvalReceipt"],
  ["app/src/main/java/app/conductor/tools/ToolRegistry.kt", "AppOperationApprovalReceipt"],
  ["app/src/main/java/app/conductor/runtime/ConductorRuntime.kt", "approvedApproval"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidIntentModels.kt", "requiresUserFinalTap"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidIntentModels.kt", "AndroidIntentLaunchStatus"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidIntentLauncher.kt", "fun launch"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidContextIntentLauncher.kt", "context.startActivity"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidContextIntentLauncher.kt", "ActivityNotFoundException"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidContextIntentLauncher.kt", "FLAG_ACTIVITY_NEW_TASK"],
  ["app/src/main/java/app/conductor/tools/intents/RecordingAndroidIntentLauncher.kt", "launchedPlans"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidIntentPlanner.kt", "android.intent.action.SENDTO"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidIntentPlanner.kt", "android.intent.action.INSERT"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidIntentPlanner.kt", "google.navigation:q"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidIntentPlanner.kt", "android_intent:calendar_hold_tentative"],
  ["app/src/main/java/app/conductor/tools/intents/AndroidIntentPlanner.kt", "android_intent:maps_route_preview"],
  ["app/src/main/java/app/conductor/planner/OutdoorActivityPlanner.kt", "calendar.create_hold"],
  ["app/src/main/java/app/conductor/planner/OutdoorActivityPlanner.kt", "maps.open_route"],
  ["app/src/main/java/app/conductor/planner/OutdoorActivityPlanner.kt", "publicPostStepIfRequested"],
  ["app/src/main/java/app/conductor/planner/OutdoorActivityPlanner.kt", "facebook.post"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "setContent"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "CustomAppPlaybookSeeder.seedDefaults"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "registryProvider ="],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "customPlaybooks = recordStore.appOperationPlaybooks()"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "RecordBackedAccountSessionStore"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "AccountSessionMobileAuthTokenProvider"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "accountSession?.userId"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "rememberLauncherForActivityResult"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "ActivityResultContracts.RequestPermission"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "Manifest.permission.RECORD_AUDIO"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "microphonePermissionGranted"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "voice.permission_requested"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "voice.permission_denied"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "microphone_permission_denied"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "UserPolicyStore"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "ApprovalDecisionStore"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "AndroidConductorRecordStoreFactory.create(applicationContext)"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "VoiceSessionController"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "VoiceHandoffRunner"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "AndroidSpeechCapture(applicationContext)"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "AndroidSpeechOutput(applicationContext)"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "ProductionRealtimeModelTransport"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "FallbackRealtimeSessionTokenProvider"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "HttpRealtimeSessionTokenProvider"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "RecordingRealtimeSessionTokenProvider"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "autonomyMode = userPolicy.mode.name"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "ToolRegistry"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "RecordBackedAppOperationSessionStore"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "RecordBackedAppOperationApprovalReceiptLedger"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "RecordBackedAppOperationQueue"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "queuedAppOperations = recordStore.queuedAppOperations()"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "appOperationSessions = recordStore.appOperationSessions()"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "graphGrants = recordStore.graphGrants()"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "appAgentGrants = recordStore.appAgentGrants()"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "onDataGrantRevoked"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "onDataGrantRestored"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "onAppAgentGrantRevoked"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "onAppAgentGrantRestored"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "graph.grant_revoked"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "graph.grant_restored"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "app_agent.grant_revoked"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "app_agent.grant_restored"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "onAppSessionAutonomySelected"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "onAppSessionRevoked"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "app_agent.session_revoked"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "revoked = true"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "operator.session_autonomy_updated"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "onStopAutonomy"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "AutonomyMode.ASK_ONLY"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "clearQueuedAppOperations"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "autonomy.stopped"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "autonomy_stopped_by_user"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "onAppHandoffGranted"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "saveAppOperationSession"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "queued.primaryActionLabel == \"Review inputs\""],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "queued.primaryActionLabel == \"Approve exact content\""],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "operator.handoff_review_required"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "existingSession?.loginProof"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "allowedPlaybookIds = session.allowedPlaybookIds + queued.request.playbookId"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "allowedSourceIds = session.allowedSourceIds + queued.request.requiredSourceIds"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "user_confirmed_app_handoff"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "resolveQueuedAppOperation"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "operator.session_granted"],
  ["app/src/main/java/app/conductor/launcher/ConductorLauncherActivity.kt", "AndroidContextIntentLauncher(applicationContext)"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onVoicePressed"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "EmergencyStopRow"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Stop autonomy"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onStopAutonomy"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "AutonomyModeRow"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "DataAccessSection"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Data access"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "AppAgentAccessSection"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Agent data access"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onDataGrantRevoked"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onDataGrantRestored"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onAppAgentGrantRevoked"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onAppAgentGrantRestored"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Revoke"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Restore"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "AppSessionSection"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "App autonomy"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "session.allowedSourceIds"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Expires:"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Login proof:"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Verified:"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onAppSessionAutonomySelected"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onAppSessionRevoked"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Revoke agent"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "ApprovalSection"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "AppHandoffSection"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Login, grants, and app-operation inputs"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "requiredUserAction"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "Autonomy:"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "handoff.primaryActionLabel"],
  ["app/src/main/java/app/conductor/ui/ConductorLauncherScreen.kt", "onAppHandoffGranted"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "AppHandoffUi"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "primaryActionLabel"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "autonomyContext"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "AppSessionUi"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "allowedSourceIds"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "loginProofMethod"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "loginProofSubject"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "loginProofVerifiedAtIso"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "val revoked: Boolean"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "DataGrantUi"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "AppAgentGrantUi"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "graphGrants"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "appAgentGrants"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "toDataGrantUi"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "toAppAgentGrantUi"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "appOperationSessions"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "toAppSessionUi"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "queuedAppOperations"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "toAppHandoffUi"],
  ["app/src/main/java/app/conductor/ui/LauncherUiState.kt", "toLauncherUiState"]
];

const missing = requiredFiles.filter((file) => !fs.existsSync(path.join(root, file)));
if (missing.length > 0) {
  console.error("Missing files:");
  for (const file of missing) console.error(`- ${file}`);
  process.exit(1);
}

const missingText = [];
for (const [file, text] of requiredText) {
  const body = fs.readFileSync(path.join(root, file), "utf8");
  if (!body.includes(text)) {
    missingText.push(`${file}: ${text}`);
  }
}

if (missingText.length > 0) {
  console.error("Missing required text:");
  for (const item of missingText) console.error(`- ${item}`);
  process.exit(1);
}

console.log(JSON.stringify({
  status: "ok",
  requiredFiles: requiredFiles.length,
  requiredInvariants: requiredText.length
}, null, 2));
